### ISSUE TITLE
How to get Item Warehouse locations from EOL?

### ISSUE THREAD

**Issue by kingcoen** [picqer/exact-php-client#109]
I have looked in almost every file to find a possible solution to get the Stock Location, anyone has a solution yet?

**Comment by stephangroen** [comment]
Where is this located in the Exact Online docs? https://start.exactonline.nl/docs/HlpRestAPIResources.aspx?SourceAction=10

**Comment by GewoonRoy** [comment]
@kingcoen Could be some relations with Warehouse. You need to puzzle a bit though, because it will finally need to relate to an Item.

https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=InventoryWarehouses
https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=InventoryStorageLocations
https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=InventoryItemWarehouseStorageLocations
