### ISSUE TITLE
SalesItemPrice

### ISSUE THREAD

**Issue by WebDevTmas** [picqer/exact-php-client#113]
SalesItemPrice is missing from the API
https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=LogisticsSalesItemPrices

Will this be implemented?

**Comment by larswiwi** [comment]
I implemented it a few days ago, I don't know how to update the code, maybe someone else could add it?
Note that the $primaryKey is public instead of static.
This is because the find on ID will not work easily since you don't know the salesitemprice ID. 
To get it, I set primaryKey on Item and use findWithSelect('productGUID', 'ID, Currency') etc...

`<?php namespace Picqer\Financials\Exact;

/**
 * Class SalesItemPrice
 *
 * @package Picqer\Financials\Exact
 * @see https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=logisticsSalesItemPrices
 *
 * @property Guid $ID Primary key
 * @property Guid $Account ID of the customer
 * @property String $AccountName Name of the customer account
 * @property DateTime $Created Creation date
 * @property Guid $Creator User ID of creator
 * @property String $CreatorFullName Name of creator
 * @property String $Currency The currency of the price
 * @property String $DefaultItemUnit The default unit of the item
 * @property String $DefaultItemUnitDescription The description of the default item unit
 * @property Int32 $Division Division code
 * @property DateTime $EndDate Together with StartDate this determines whether the price is active
 * @property Guid $Item Item ID
 * @property String $ItemCode Code of Item
 * @property String $ItemDescription Description of Item
 * @property DateTime $Modified Last modified date
 * @property Guid $Modifier User ID of modifier
 * @property String $ModifierFullName Barcode of the item (numeric string)
 * @property Double $NumberOfItemsPerUnit This is the multiplication factor when going from default item unit to the unit of this price.For example if the default item unit is 'gram' and the price unit is 'kilogram' then the value of this property is 1000.
 * @property Double $Price The actual price of this sales item
 * @property Double $Quantity Minimum quantity to which the price is applicable
 * @property DateTime $StartDate Together with EndDate this determines whether the price is active
 * @property String $Unit The unit code of the price
 * @property String $UnitDescription Description of Unit
 */
 class SalesItemPrice extends Model
{
     use Query\Findable;
    use Persistance\Storable;

	public $primaryKey = 'ID';
   
	protected $fillable = array(
        'ID',
        'Account',
        'AccountName',
        'Created',
        'Creator',
        'CreatorFullName',
        'Currency',
        'DefaultItemUnit',
        'DefaultItemUnitDescription',
        'Division',
        'EndDate',
        'Item',
        'ItemCode',
        'ItemDescription',
        'Modified',
        'Modifier',
        'ModifierFullName',
        'NumberOfItemsPerUnit',
        'Price',
        'Quantity',
        'StartDate',
        'Unit',
        'UnitDescription'
    );

    protected $url = 'logistics/SalesItemPrices';
	
}
`

**Comment by WebDevTmas** [comment]
I'll check it out next week to see if it works properly and then make a pull request here crediting you

**Comment by dovereem** [comment]
Thx for adding SalesItemPrice! I noticed it missing as well and was glad to see it was added right when I needed it. 
Could the Picqer guys create a new version with this Model? I'm currently requiring dev-master in composer, but I'd rather not :)

**Comment by stephangroen** [comment]
@dovereem Will do, sorry for the delay!
