### ISSUE TITLE
Transactions Journal(s)

### ISSUE THREAD

**Issue by PaulVanDeKamer** [picqer/exact-php-client#119]
Hi,

Trying to get all transactions from a journal. Can someone provide an example?

This is what i have at the moment:

try {
    $transactions = new \Picqer\Financials\Exact\Transactions($connection);
	$result = $transactions->filter('', '', '', ['$top'=> 1]);

    foreach ($result as $trans) {
       print_r ( $trans );
    }

} catch (\Exception $e) {
    echo get_class($e) . ' : ' . $e->getMessage();
}

Cheers,

Paul

**Comment by GewoonRoy** [comment]
Hello @PaulVanDeKamer 

It is possible to get more records with 'selection' fields.

Because you add ['$top'=> 1] it will limit the results to 1. What you could try is add 'selection' fields as the 3rd parameter, if i'm right, instead of using ['$top'=> 1]. Also add a filter to the 1st param with something like: 'Journal eq _JournalCode_'.
