### ISSUE TITLE
Auto Login

### ISSUE THREAD

**Issue by jasonkx** [picqer/exact-php-client#220]
Hi
when I use the example Script I get redirected to a page where i should login with username and password. After Logging in the browser redirects to my redirectUrl.

This can obvisouly not be the way to use the php-client for an Automatic PHP API. 

So my question is how can i automatically login without manually typing username and password into the browser?

**Comment by niekoost** [comment]
Hi jasonkx,

this is the way it should work, since it is a Oauth2 sequence. You should make sure that the refresh_key is stored and used for each request, after a successful authorization sequence, than you won't have to enter the username and password anymore.

Check out https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-oauth-eol-oauth-dev-impleovervw

Kind regards, 
Niek

**Comment by duckchip** [comment]
@niekoost Is there a way of using a curl POST request with the credentials to obtain the authorization code?

I'm using a cronjob to implement the data in our database and I don't want to go through a browser.

Kind regards

Tristan

**Comment by versdivers** [comment]
@duckchip Just make a button that 'connects' and redirects to the login page if you don't have an auth code and refresh token. You should never save credentials of Exact in your software.
