### ISSUE TITLE
Count or log all requests to Exact

### ISSUE THREAD

**Issue by meijdenmedia** [picqer/exact-php-client#255]
Exact Online has announced to have API limits on their REST API.
What is the best way to count/log all outgoing API calls to Exact Online?

Duplicate of: https://github.com/picqer/exact-php-client/issues/238

**Comment by stephangroen** [comment]
The best way is to not count anything locally. The headers that Exact Online returns should be used to know if you have room for any more requests. As the [documentation](https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Simulation-gen-apilimits) states three headers are returned, which is quite usual for API's with rate limits. 

The easiest is to check the X-RateLimit-Remaining header to know how many calls you can still do. If this falls below 1 (or add some to keep a safe remaining count) you postpone all remaining calls until the time stated in the header X-RateLimit-Reset at which you continue to do the calls.

**Comment by EiseWielinga** [comment]
I didn't find a way to get the headers myself. 
The functions in the Connection class (link below) will parse the response to only return the body using the parseResponse function, making it impossible to get the headers? 
By the sound of your answer, it feels that it could be done quiet easily. However I don't see how.  
Is there an example how to?

(https://github.com/picqer/exact-php-client/blob/master/src/Picqer/Financials/Exact/Connection.php) 

Kind regards,
Eise

**Comment by stephangroen** [comment]
Hi Eise,

I'm working on this functionality, but I don't seem to get these headers yet or somewhere Guzzle filters them out. I have to put in some more time to figure this out.

What I have basically done so far (to point you in a direction):

- Added class properties rateLimit, rateLimitRemaining and rateLimitReset to the Connection class
- In the parseResponse method in the Connection class you get the Response object, tried to extract the headers there but the response doesn't seem to contain them.

```php
        $this->rateLimit = $response->getHeader('X-RateLimit-Limit');
        $this->rateLimitRemaining = $response->getHeader('X-RateLimit-Remaining');
        $this->rateLimitReset = $response->getHeader('X-RateLimit-Reset');
```

Need to find some more time to do some digging.

**Comment by EiseWielinga** [comment]
Hey stephan,

Thank you for replying on such short notice.
I did some little digging myself. Perhaps I'm being a bit too 'Kapitein Vanzelfsprekend', I'm a junior dev, but from what I understood.
I think you have to add the headers also in the request otherwise it wouldnt be in the response (http://guzzle3.readthedocs.io/http-client/client.html#headers)
If this is not the problem try using the getHeaders() to see what headers are in the response?

I hope this speeds up the process for you.

**Comment by EiseWielinga** [comment]
Hey Stephan,

Any updates regarding this issue?

Kind regards,
Eise Wielinga

**Comment by DannyvdSluijs** [comment]
Perhaps late to the game, but you could add middleware to the guzzle http client like suggested in #288. Here perhaps a tap would be more logical injecting a value object to be updated with the values returned by the response headers.

```php
$valueObject = new \stdClass();
$connection->insertMiddleWare(Middleware::tap(
    null,
    function($request, $options, $response) use ($valueObject) {
        $response->then(function (Response $response) use ($valueObject) {
            $valueObject->limit = $response->getHeader('X-RateLimit-Limit');
            $valueObject->remaining = $response->getHeader('X-RateLimit-Remaining');
            $valueObject->limit = $response->getHeader('X-RateLimit-Reset');
        });
    }
));
```

After calling the API the `$valueObject should contain all the info you would need. For me it didn't as it seems the demo accounts of Exact Online do not contain rate limiting.

**Comment by stephangroen** [comment]
> For me it didn't as it seems the demo accounts of Exact Online do not contain rate limiting.

Hmm, that could be the problem I have too. I'll contact them to check if that's true.

**Comment by meijdenmedia** [comment]
Thanks for everything guys! Too bad they don't provide the headers so we can at least test with it..

**Comment by stephangroen** [comment]
According to this page the limits should have been implemented by now: https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-ReleaseNote-rn-1812-rn-appcenterapilimits

However I still do not seem to get any headers regarding the rate limits in the response. I'll ask Exact if that is correct.

**Comment by softtouch-ruben** [comment]
We are having a lot of problems since a week or so because of both the limits per day and the limits per second. A successful call returns values for X-RateLimit-Limit and the X-RateLimit-Remaining in the header. When either the daily limit or the limit per minute is exceeded a 429 response code is given, but the headers are not shown. Therefor it is not clear if the daily or the calls per minute limit was exceeded.

Another note about the 60 calls per minute limitation. According to the documentation (https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Simulation-gen-apilimits) 60 calls can be made per minute without restrictions. After that each second within that minute another call can be made. However, I figured that this is incorrect. The duration of the limitation is not one minute, but two minutes. Thought this might be helpful in finding a solution. 

There is a possibility that the limitation per minute is only applicable when the daily limit has been set higher than the default 50000, which was necessary for us. 

For what it's worth, I forked this repo to take the limitations per minute into account. It is a very quick and dirty solution and has not been tested thoroughly. I expect, this is far from the best way to go about it, but it's something. (https://github.com/SoftTouch-bvba/exact-php-client). When using it the lines with "\Illuminate\Support\Facades\Log" in it should be removed. 
When the pause for minute limit is set to true (`$connection->setPauseForMinuteLimit(true);`) and 60 calls have been made, the connection will sleep for 2 minutes before making a next call. 
Half'n hour sleep for maintenance mode has also been added and can be set with `$connection->setPauseForMaintenance(true);`. Another quick and dirty fix.

@stephangroen, I hope you can get a better fix soon, or perhaps point me in a better direction to tackle these issues.

**Comment by stephangroen** [comment]
Stil in contact with Exact, I don't get any RateLimit headers back from them in my test account.

**Comment by alexjeen** [comment]
Maybe a bad place to start it here, but if you really need to post in higher volumes it is better to use the XML API.

**Comment by remo-moddit** [comment]
Exact seems to output the headers now. Putting this code in the `parseResponse` method works nicely:

```
            $this->rateLimit = (int) $response->getHeaderLine('X-RateLimit-Limit');
            $this->rateLimitRemaining = (int) $response->getHeaderLine('X-RateLimit-Remaining');
            $this->rateLimitReset = (int) $response->getHeaderLine('X-RateLimit-Reset');
```

**Comment by justijndepover** [comment]
Any update regarding this issue?

**Comment by meijdenmedia** [comment]
I implemented a working solution for Laravel applications, see: https://github.com/picqer/exact-php-client/pull/355

**Comment by stephangroen** [comment]
It was long due, my apologies for that. I've just released v3.19.0 of the library, with support for getting the rate limits. You can find the PR here for the technical details: https://github.com/picqer/exact-php-client/pull/363

I have also added a section to the README for more information: https://github.com/picqer/exact-php-client#rate-limits

The `ApiException` now has a code that is the HTTP status code from the response. So you can check on `$apiException->getCode() === 429` to see if it was thrown because of a rate limit hit.

**Comment by izub** [comment]
@stephangroen one tiny issue is that when an ApiException is thrown for a bad response (like a 429), the extractRateLimits isn't called since it's only added in parseResponse. 
There should also be an extractRateLimits in parseExceptionForErrorMessages. Otherwise it's a bit difficult to determine whether the minutely or daily limit was hit :)

**Comment by izub** [comment]
Please find my PR for the above here: #373
