### ISSUE TITLE
How to set the payment of the invoice to complete?

### ISSUE THREAD

**Issue by LiquidSebbey** [picqer/exact-php-client#260]
When created an invoice, how to set the invoice to "payment already done" ? (So, there is no payment left for the created invoice)?

**Comment by Louren** [comment]
Hello @LiquidSebbey,

As far as I'm aware, you have two options. Your question is not directly related to this Github though (as it's more related to the general usage of EOL). However, I'll try to help as we (at Uw Computerstudent) have working solutions for your problem in place, and I'm happy to share.

1. You can create a memo booking using the API. This would be a booking of i.e. bank/cash to debtors, cancelling the outstanding amount. We use this approach for our PSP payments (i.e. we book 'to receive from psp' to 'debtors'). EOL automatically reconciles ('afletteren') the invoice so that it's marked as 'paid', _if_ amounts match exactly. Disadvantage: lots of memo bookings, hard to manage/audit. 
2. You can add a product/invoice line that makes the invoice total amount 0. We do use this approach for gift cards. You can consider the usage of a gift card as us buying it back from the customer. Then, it makes sense to add it to the invoice as a negative amount. Be sure to set the appropriate VAT codes. 

Good luck solving your problem!

**Comment by YoranScholiers** [comment]
Hi @Louren, can you perhaps show some code that does what you described in number one?
I currently succeeded in searching/creating an Account, SalesInvoices + Lines and PrintedSalesInvoices but I just can not figure out how to proceed with the BankEntries. At least I think I need those entries?

I realise that this is not related to this Github but the Knowledge Hub is not really helpful.

**Comment by Louren** [comment]
Hi @yohancreemers,

In our case, we use a memo (memoriaal) booking, so you don't need to make any BankEntries. Since both work the same way, the choice mainly depens on your preference in the financial administration. 

I could show you the code, but it's 'old' code using the XML api of Exact, so not based on this Picqer client. However, I suppose you should be able to use the `GeneralJournalEntry` object along with `GeneralJournalEntryLine` (or maybe `BankEntry` and `BankEntryLine`) to accomplish the same. We'll look into this at some point in time, but not within the next month I suppose, so not sure if that helps you.

In general, remember that both a BankEntry and a GeneralJournalEntry generally consist of at least resp. 1 and 2 ...Lines. Have a look at the Exact Online gui first if this doesn't make sense right now. 

I agree that the provided information isn't really exhaustive, but then again, I understand that this client is the internal work of Picqer that they're sharing for free.
