### ISSUE TITLE
Item Price for Account

### ISSUE THREAD

**Issue by Aubinga** [picqer/exact-php-client#273]
Hi,

is there a way to get a itemprice for an account?

Ive PriceLists for Accounts with discounts some ItemGroups. With this client I get everything except the discount or the itemprice for an account.

With \Picqer\Financials\Exact\Account($connection);	 I get all my clients/accounts
With \Picqer\Financials\Exact\Item($connection);	 I get all items

Now I want display diffrent prices for the diffrent accounts. 
Like 
User A, Item A 10,00
User B, Item A   9,90
...

Any ideas?

Thank you

**Comment by alexjeen** [comment]
Indeed the prices are not returned with the Items because they can depend on some factors in Exact Online.

You have to issue a GET to one of these two endpoints:

![image](https://user-images.githubusercontent.com/1567497/44423319-bd496900-a57d-11e8-98a2-5af89572cde1.png)

With SalesPriceListDetails you can also apply some OData filters to filter by Account (per your request).
