### ISSUE TITLE
Changes in API

### ISSUE THREAD

**Issue by kneibdev** [picqer/exact-php-client#311]
I got this message from Exact, will this still work with this code? I'm not so familiar with OAuth.

> You receive this e-mail since our logging shows that your application, linked to Exact Online, is using old refresh tokens in order to connect to Exact Online. 
> If you are not the supplier or developer of the application, please send this message as soon as possible to your supplier or developer of this application.
> 
> As per the 31st of December it will not be possible anymore to re-use a refresh token more than once. 
> Every time your application requests a new access token, using a refresh token, alongside that refresh token, you are also granted a new refresh token. 
> 
> This new refresh token has always been intended for applications to retrieve new access with, this way applications can maintain their high security standards. 
> 
> The complete flow of how  access and refresh tokens should be used is described in step 4 of our OAuth tutorial, please see: https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-oauth-eol-oauth-dev-step4
> 
> Make sure these changes are applied before the 31st of December as from that date, the application will not be able exchange data with Exact Online if it still uses old refresh tokens.
> 

I used the example with storage.json

Thanks in advance.

**Comment by CompactCodeEU** [comment]
Don't you just need to save the new refresh token that you get when refreshing?

**Comment by nickvleeuwen** [comment]
Ive got the same mail. I didn't use the optional option to use and store 'expires_in' in the authorization process.
I did implement it now, but this shouldn't solve the problem exact describes in the mail:

> As per the 31st of December it will not be possible anymore to re-use a refresh token more than once.

Beside the optional option I already did everything as described by the package documentation.

I'm curious if there is anyone else having the same problems?

**Comment by DannyvdSluijs** [comment]
@kneibdev @nickvleeuwen I've added [a small snippet](url
https://github.com/picqer/exact-php-client/wiki/Exact-php-client-tips#persisting-new-access--refresh-token-when-newly-acquired) which shows how to hook into the connection in order to persist the tokens details to a storage option of your choice (Redis, Mysql, File) hope this helps.

**Comment by Liiva** [comment]
I've also got this email. In my setup every time I create the Exact\Connection instance, I fetch access token, refresh token and token-expires values from the database and (if they exist) add them to the connection. Then I've implemented the setTokenUpdateCallback to simply update these values.

Now it's a bit unclear to me whether I need to update this setup or will it just continue working after the 31st of December. Anyone can confirm this?

**Comment by HeineDeelstra** [comment]
We use the library on a website where multiple endusers may be active and cause requests to the Exact Online backend.

While the library provides a callback to persist an updated token, there's no infrastructure to ensure only one (website) request refreshes the token. I'm assuming that the use of the old refresh token happens when multiple requests race to refresh a token.

1. Req1 obtains the persisted token token0, determines a refresh is needed and requests a new token from the Exact Online endpoint.
2. Req2 happens in the mean time, obtains the persisted token token0, determines a refresh is needed and requests a new token from the Exact Online endpoint.
3. Req1 obtains an updated token token1 from the endpoint and persists the token via the update callback
4. Req2 obtains an updated token token2 from the endpoint and persists the token via the update callback

Depending on which requests "wins" either token1 or token2 gets persisted and Exact Online will count this as the use of an old refresh token. After Dec 31st one of the requests will get an error message instead.

Would it be possible to add "lock/unlock" callbacks to allow to wait on a token refresh? An application-level workaround would be to lock on each call to the ExactOnline backend.

**Comment by hqmatics** [comment]
We also received this e-mail from Exact.
Debugging the requests I found that the same refresh token is being returned by Exact. Anybody else has this issue?

**Comment by i6media** [comment]
We've also got the e-mail, 

Is this going to be an out-of-the-box fix which resolves the issue by just updating to the latest release  of the repository, or is manual action still required afterwards?

**Comment by hqmatics** [comment]
It seems Exact has updated the API because we now receive new refresh tokens and got confirmation from Exact we are indeed using new refresh tokens.

**Comment by MarkCorneth** [comment]
> We've also got the e-mail,
> 
> Is this going to be an out-of-the-box fix which resolves the issue by just updating to the latest release of the repository, or is manual action still required afterwards?

Also curious about this.

**Comment by pavoxbv** [comment]
As far as I can see no further action is needed. I verified that upon connection a new refrehstoken is supplied bij the ApI, stored and used bij the code on the next connection.
