### ISSUE TITLE
Adding stock to product

### ISSUE THREAD

**Issue by akerssies** [picqer/exact-php-client#446]
Hello, 

I've been working on a way to add stock quantity to a product and to my understanding i need InventoryStockCounts (class StockCount) to do that.
To add a stockcount the StockCountDate, StockCountLines and Warehouse properties are mandatory. 
To add StockCountLines the Item and StockCountID properties are mandatory but the StockCount is not created so there is no StockCountID.

First question: Is it correct that i need to use the InventoryStockCounts to add the stock quantity? 
Second question: If i indeed need to use that, how can i add it without having the StockCountID?

https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=InventoryStockCounts
https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=InventoryStockCountLines

**Comment by DannyvdSluijs** [comment]
@akerssies sad to see your issue was left unanswered. Hope you came to another way of answering your question.
For the proper order this repository contains an "unofficial" PHP API client done by volunteers. 

The question you're asking is more specific to API usage and would be better to ask to the support staff of Exact Online. On which API calls to make and in which order.

**Comment by remkobrenters** [comment]
Thank you @DannyvdSluijs this concludes this question. I will close this issue.
