### ISSUE TITLE
Refresh tokens concurrency issues

### ISSUE THREAD

**Issue by WeTurkstra** [picqer/exact-php-client#487]
Hi everyone, 

We also have some issue with refresh tokens:
Could not acquire or refresh tokens [http 401].

When there are multiple requests at the same time we still find that locking is not sufficient. 
We implemented all the provided callback functions to start locking, refreshing, updating and release locks.
I followed some of the other threads and i think i implemented the callbacks correctly.

But we still occasionally get a 401 on token refresh.
We are breaking our head over this. Could anyone please give some insights on what we could do more?

We use Symfony/lock packages for locking.
Our Connection object:
```
$connection = new Connection();
$connection->setRedirectUrl($this->getRedirectUrl($connector));
$connection->setExactClientId($_ENV['EXACT_CLIENT_ID']);
$connection->setExactClientSecret($_ENV['EXACT_CLIENT_SECRET']);
$connection->setAccessToken($metaData['accessToken']);
$connection->setRefreshToken($metaData['refreshToken']);
$connection->setTokenExpires($metaData['tokenExpires'] ?? 100);

//At start of receiving token lock it for other processes
$connection->setAcquireAccessTokenLockCallback(function () use ($lock, $lockName) {
    $this->logger->debug(sprintf('%s - Aquire Lock', $lockName));
    $lock->acquire(true);
});

//Release the lock when done aquiring accesstokens
$connection->setAcquireAccessTokenUnlockCallback(function () use ($lock, $lockName) {
    $this->logger->debug(sprintf('%s - Release Lock', $lockName));
    $lock->release();
});

//After lock release, tokens could be refreshed!
//We should refresh the connection object with the new values
//Then 2 refresh call might not happen within the same few minutes
$connection->setRefreshAccessTokenCallback(function ($self) use ($connector, $lockName) {
    $this->logger->debug(sprintf('%s - Refreshing tokens', $lockName));
    /** @var Connection $self */
    $connectorRepository = $this->entityManager->getRepository(Connector::class);
    $connector = $connectorRepository->find($connector->getId());

    $metaData = $connector->getMetadata();
    $self->setAccessToken($metaData['accessToken']);
    $self->setRefreshToken($metaData['refreshToken']);
    $self->setTokenExpires($metaData['tokenExpires'] ?? 100);
});

//When new Tokens are aquired store them before unlocking.
//This way other waiting processes will have access to the new tokens.
$connection->setTokenUpdateCallback(function ($connection) use ($connector, $lockName) {
    $this->logger->debug(sprintf('%s - Updating tokens', $lockName));
    $connector->addMetadata('accessToken', $connection->getAccessToken());
    $connector->addMetadata('refreshToken', $connection->getRefreshToken());

    //set expiring 5 mins before actual expiration.
    //The access token has to be valid until the END of the request at Exact.
    $connector->addMetadata('tokenExpires', $connection->getTokenExpires());

    $this->entityManager->persist($connector);
    $this->entityManager->flush();
});
```

**Comment by marnickmenting** [comment]
We encounter the same problem. The only difference is we don't use locks or anything, we have 1 worker that processes the jobs so they never overlap. I can't wrap my head around it. Randomly we receive code 401 with the message: "Old refresh token used. This library should just handle that correctly, right?

**Comment by remkobrenters** [comment]
The problem lies not in the way the library works but in they way Exact enforces rate limits mixed with some weird glitches. It can happen that Exact returns an error (triggering an exception) while still returning a new token.

Some things you might want to look into is to see if, even though a client exception is thrown, Exact sent back a new token. Also be prepared that, even if all is working stable for weeks, it can happen Exact for some reason returns an error that breaks connection so a good flow for restoring broken connections is essential.

**Comment by arjan-kwikqy** [comment]
Im experiencing the same issue. Already reached out to Exact. The only response i got it: yeah your request is wrong...
I also tried to refresh the tokens with an endpoint call with Guzzle and the response i get is: {"error":"invalid_request","error_description":"Signed data extraction has failed"}

Still checking the issue because help from Exact is apparently not possible...

**Comment by WeTurkstra** [comment]
@remkobrenters So your saying that even if i fix the concurrency issue. There might still be problems when Exact randomly returns an error?

And what would be a good flow for restoring broken connections. Because in my opinion that would mean that a client has to reauthorize! And i would like to keep taht to a minimum.

**Comment by remkobrenters** [comment]
Tough question. Our experience is that in some cases with some clients the connection out of the blue breaks without big differences in the process that runs on a daily base for example. My best guess so far is that in runs into the rate limit without triggering a rate limit exception. 

Regarding restoring connections: I understand and agree but due to the sensitivity of the connection and it's unexpected responses in some occasions I recommend implementing a process for reinstating tokens that is built like it is used very often. If all works out you won't need it for months in a row but it will be needed at some point.

**Comment by marnickmenting** [comment]
> The problem lies not in the way the library works but in they way Exact enforces rate limits mixed with some weird glitches. It can happen that Exact returns an error (triggering an exception) while still returning a new token.

Is a token always returned or does it sometimes invalidate old refresh token without receiving a new one? I can't find any refresh token in the response body when the random error happens.

**Comment by remkobrenters** [comment]
I suspect Exact from sometimes invalidating a refresh token without providing a new one. The only error I know for sure that returns a new refresh token is 429 (rate limit).

**Comment by DannyvdSluijs** [comment]
I suspect when asking Exact you’ll need to provide logging. See https://github.com/picqer/exact-php-client/wiki/Exact-php-client-tips#log-api-request-and-response on how you can inject logging middleware. Perhaps you can find some pattern that might lead to more details on the issue.

**Comment by theemstra** [comment]
We're running into the same issue. We're not running concurrent jobs, we're testing this right now by running a cron job every x minutes and sometimes out of the blue it will just return 401 Could not aquire or refresh tokens.
Will contact support about this

**Comment by casperbakker** [comment]
With #482 the token will be refreshed if it expires mid-execution. For example if you are executing commands for more then 10 minutes.

But Exact returning tokens that expire right away is not something we can fix in the client. We have that same issue with only 1 customer using Exact. So I will close this issue for now. If there is more news about this and there is something we can fix in this client, please feel free to open a new issue.
