### ISSUE TITLE
change salesorder remarks problem after 8 june 2021. Error 500: Not allow to update in Basic : Warehouse

### ISSUE THREAD

**Issue by jackmagielse** [picqer/exact-php-client#492]
I try to update the remarks in a salesorder and when i do the save i get the error "Error 500: Not allow to update in Basic : Warehouse". The update worked up to 8 june 2021. from 9 june 2021 it doesnt work anymore.
I contacted exact and they told me that with a basic contract you are not allowed to update the warehouse because there is only 1. I tried to leave the warehouseid empty but then i got the error "Picqer\Financials\Exact\ApiException : Error 400: Error processing request stream. Error encountered in converting the value from request payload for property 'WarehouseID' to type 'Guid', which is the property's expected type. See inner exception for more detail."

**Comment by DannyvdSluijs** [comment]
@jackmagielse I've took the liberty adding some formatting to your original question. This might help others in getting to read the message better

> I've tried to update the remarks in a sales order and when save I get an error `Error 500: Not allow to update in Basic : Warehouse`. This update used to work up to the 8th of June 2021. From 9 June 2021 it doesn't work anymore.
>
>I've contacted Exact and they told me that with a basic contract you are not allowed to update the warehouse, because there is only 1. I've tried to leave the `warehouseid` empty but then I got the error 
> ```
>Picqer\Financials\Exact\ApiException : Error 400: Error processing request stream. 
>Error encountered in converting the value from request payload for property 'WarehouseID' to type 'Guid', which is the property's expected type. 
>See inner exception for more detail.
>```

So if I've can summarise you cannot update the remark on a sales order as you cannot update the warehouse. Leaving it empty throws the HTTP 400 error. Could you provide the code you using in order to try and make a repro. Did the people from Exact tell anything if a warehouseID should be omitted at all when on a basic contract?

It seems this API client isn't aware of the type of contract you're using. So that might be the feature/fix you're after when you raised the ticket but forgot to mention?

**Comment by gekophetweb** [comment]
Has anybody been able to solve this issue? 
I am currently having the same issue and all I am doing is getting an existing order from Exact and updating the description

`$salesOrder  = new \Picqer\Financials\Exact\SalesOrder(parent::getConnection());
$object      = $salesOrder->find($orderId);
 $object->Description .= " extra text"
 $object->update();
`
 We do get a proper order back from the API but cannot update them because of the error mentioned above.
 Is this something we have to contact Exact about?

**Comment by gekophetweb** [comment]
@jackmagielse Have you been able to resolve the issue yet?
If so, how did you resolve this problem?

**Comment by Oizopower** [comment]
Having the exact same issue as described above, If i try to update the SalesOrder then i receive the error message: 
Error 500: Not allow to update in Basic : Warehouse

**Comment by remkobrenters** [comment]
As this seems to be an issue on the side of Exact (license limitation or something) I will close this.
