### ISSUE TITLE
waitIfMinutelyRateLimitHit not working

### ISSUE THREAD

**Issue by dennisbuijsgmailcom** [picqer/exact-php-client#521]
Hi

I think the function Connect::waitIfMinutelyRateLimitHit is not working. When the MinutelyLimitRemaining is zero, the resetInSeconds are not correct, for me -245 seconds. The time different of the Exact server time and the local server time is the problem.

Best regards
Dennis

**Comment by dennisbuijsgmailcom** [comment]
I made a fix and now it is not generating an API limit problem anymore. 
Basically the minutelyLimitResetServerTime is generated with the local server time just when a new time slot of 60 calls is started.
Ofcourse when using the connection class, reuse it when doing the API calls, otherwise the minutelyLimitResetServerTime will be reset everytime.

/**
     * @var bool
     */
    protected $minutelyLimitResetServerTime; 

protected function waitIfMinutelyRateLimitHit()
    {
        if (! $this->waitOnMinutelyRateLimitHit) {
            return;
        }

        $minutelyReset      = $this->getMinutelyLimitReset();        
        $minutelyLimit      = $this->getMinutelyLimit();
        $minutelyRemaining  = $this->getMinutelyLimitRemaining();
        
        if (!isset($this->minutelyLimitResetServerTime)) {
          $this->minutelyLimitResetServerTime= time()+60;	         
        }
        
        if ($minutelyRemaining >= ($minutelyLimit-1)) {
	        $this->minutelyLimitResetServerTime= time()+60;	         
	      } 	             

        if ($this->getMinutelyLimitRemaining() === 0 && $minutelyReset) {
            // add a second for rounding differences            
            $resetsInSeconds = ($this->minutelyLimitResetServerTime- time()) + 1;            
            if ($resetsInSeconds > 0 && $resetsInSeconds < 60) {
              sleep($resetsInSeconds);
            } else {
              sleep(60);
            }
        }        
    }

**Comment by remkobrenters** [comment]
Are there more people who come to the same conclusion as we noticed that we see some rate limit issues here and there but I did not had time to look into this enough to conclude the origin of the problem. If the conclusion of Dennis is correct a slightly refactored version of his code would be worth a PR I think.

**Comment by alexjeen** [comment]
Hi there,

I've wrote that PR originally for the waitIfMinutelyRateLimitHit().

You do have to make sure your clock is spot on on your device. Otherwise the code will never work. time() uses UTC internally and this aligns with what Exact is using.

Also your code should look somewhat different, because the Exact rate limits always reset on 14:01:00, 14:02:00 etc. Now you jump forward +60 seconds it might delay things for longer than really needed.

I would suggest adding some code like this (your first isset is not required, will also always return true):

        if ($this->getMinutelyLimitRemaining() === null) {
            // this means we dont have any information on the rate limits, so potentially the first (real) call could fail
            $nextMinuteTs = ceil(time() / 60) * 60;
            sleep($$nextMinuteTs - time());
        }

However, it should be opt in. Because as you stated, if you reset the library (ie not use it as a singleton) between calls it will call this code every time and wait for every call to hit the 14:01:00 or 14:02:00 so stuff will get very slow for people.

By the way the /Me endpoint will always give back all 0's on the minutely endpoints. 

We havent seen any rate limit hits with Exact lately but then again we are exempted from them so I do not really feel your pain anymore 😃

**Comment by alexjeen** [comment]
Also remember, that when you are testing locally, you can have some edge case like this:

1. You are testing at 15:01:10 and you hit the rate limit so you stop
2. Exact will reset your rate limit at 15:02:00
3. You are continuing your testing at 15:01:50, the first call to /Me will not give you any info on the rate limit (it will be all 0's)
4. The first call you do, actually violates the the rate limit at Exact and you get a 429 directly

The code above, would protect you against that. But it is really only necessary if you:

1. Do concurrent API calls to the same division
2. Are developing locally and resetting the internal library between your testing 

Because this requires to you keep some state outside the library I would not actually use it in production.

If you are properly using the library in production as a singleton class & your clock is correct (so there is only one instance keeping track of these metrics from Exact) you should never have any issues!

**Comment by dennisbuijsgmailcom** [comment]
`if ($this->getMinutelyLimitRemaining() === null) {
        // this means we dont have any information on the rate limits, so potentially the first (real) call could fail
        $nextMinuteTs = ceil(time() / 60) * 60;
        sleep($nextMinuteTs - time());
    }`

I understand that you must have one call to have the limits available. But waiting for the next 60 seconds timeslot is not nice as you mentioned, to slow. Also I think you assume that the time in seconds is the same, like exact 14:01:30 is local time 14:03:30 forinstance, but if they are different like  14:01:30 and local time is 14:03:45, waiting 15 seconds until 14:04:00 is I think not waiting for the next exact timeslot.  

I use the API calls during a cron job (one connection for all api calls and one cron at the time, otherwise I also get access token expire problems), so in one run 50 orders with each order forinstance 7 api calls, waiting is acceptable before the first call with the above code. It is just like waiting a minimum of 1 minute between two cron jobs.  And yes, only needed for concurrent API calls.

But when I start the API calls after 10 minutes doing nothing, the first call is always ok, then I have the limit values. In my case also 60 calls available, doing API calls and after 26 seconds I have 0 API calls left, wait for about 35 seconds and then the next run. For me this is working, no API limit problems any more. When I do it without the fix, I get API limit problems.

**Comment by galavanto** [comment]
This still doesn't seem to work. I've implemented the new feature and it keeps returning 429 errors. Is this issue stale?

**Comment by dennisbuijsgmailcom** [comment]
For me its working. I think maybe the following can be the reason.

It is important how you make connections with Exact. When you do 100 calls within one connection instance it is working, after 60 calls it will sleep. When you do them over multiple connection instances, it is important to save the minutelyLimitResetServerTime of the previous connection. 

Before you proceed with api calls, you must check this time the same way like function waitIfMinutelyRateLimitHit , otherwise you are going to do call 61 within the 60 seconds. I do the check somewhere in my code. But I can think of the solution to use the function tokenUpdateCallback (https://github.com/picqer/exact-php-client/blob/main/example/example.php) to also retrieve and save the waitIfMinutelyRateLimitHit, so before making the connection you can check it.

hope you understand my thinking.
