### ISSUE TITLE
Pointer for people having token issues

### ISSUE THREAD

**Issue by alexjeen** [picqer/exact-php-client#523]
Hi there,

I see a lot of people are still having token issues. If you did implement the locking described in several pull requests properly there is one culprit left.. Because, we have these problems not anymore.

Rate limits, there are actually two rate limits that have gone in effect at around July when we first started seeing issues with:

1. Rate limits on the Exact API endpoints
2. Rate limits on the token endpoint

We had have several problems with both, bot 1. seems to be stable now with the function is been implemented in the library that waits for the minutelyLimit to reset actually prevent all problems there.

Due to us having still issues with authentication and tokens sometimes just breaking out of the blue (which is a problem for us because customer has to reconnect and it is a big pain every time).

We got an exemption for 2 (ie. we can now do as much calls as we want to the endpoint for the tokens) from Exact so its not being enforced anymore and now we do not have the problem anymore.

So my guess is that there is something funny going on where it would normally need to return you an error like "rate limit exceeded access token not expired" when you renew the token, actually it gets in some inconsistent state and just breaks there.

You can ask Exact support to whitelist your client ID for rate limits on the token endpoint so you can see if that solves it. If that solves it for most people, we might actually have a good case to go back to Exact with.

PS - We use the XML API mainly, because it allows us for more features and easier nested posts (ie. Exact will create master data for you if you just post in a transaction, its much easier). Since a couple of weeks, XML API also enforces the rate limits.

**Comment by marnickmenting** [comment]
We have a customer connecting 2 administrations with our software using the same Exact user. Because these administrations have their own database in our software, we were refreshing the tokens in parallel, which results in an invalidated token. We solved it now by using a separate Exact user per administration, as it would need a big rewrite to sync 2 administrations using the same session.

Maybe this helps others facing this problem :)

**Comment by remkobrenters** [comment]
Two solutions: Process each of the administrations after each other (to prevent overlapping connections and token issues) or make two separate API clients who each have their own client Id/secret and tokens.

**Comment by WeTurkstra** [comment]
We also had a lot of issues last year with invalidated tokens. We implemented the locking mechanism but this still didn't fix it completely. 

The only thing that fixed it completely was by moving all the Exact logic to a single queue. This queue could only be processed by a single worker. This is the only way to guarantee that there is single process using and refreshing the tokens. 
And since then we have had rarely any issue with tokens.(Read rarely as never). 

There is one caveat. We have a few settings which require Exact Data. There is a very rare change(it has never happend) that when you load the form,and simultanously a webhook is delivered, that you get race conditions with your tokens.
