### ISSUE TITLE
Issue in processing StockCount (ProcessStockCount)

### ISSUE THREAD

**Issue by KC031** [picqer/exact-php-client#570]
There is an issue in the current code where you get an error 403 when trying to process the stock count (see my code below).

  ```
$stock_count_process = new \Picqer\Financials\Exact\ProcessStockCount($connection);
  $stock_count_process->StockCountID = 'ddac2f61-eaaa-4ab2-b758-eb557c33a54c';
  $stock_count_process->save();
```
I based my code on the code in the example to print an invoice you have just generated. I then looked at the code of ProcessStockCount.php and added the following lines (which I found in the file PrintedSalesInvoice.php):

```
public function save()
    {
        $this->fill($this->insert());

        return $this;
    }

    public function insert()
    {
        return $this->connection()->post($this->url, $this->json(0, true));
 }
```
    
I'm not 100% sure if this was the right thing to do, but it works now.

**Comment by remkobrenters** [comment]
I think the issue is that in the default `save` method it checks if the record already exists and, if so, performs an `update` instead of an `insert` action. It normally determines if a record exists by checking if the primary key is filled. 

I wonder if it would not be better to improve the overall flow for entities that can only be created and not updated or deleted. The best way would maybe to split the `storable` trait into some parts for `save`, `update` and `delete` functionality so you can configure on a per-model base what is allowed in the first place.

Overriding methods in the model like `save` or the `exists` are making the code a bit less readable I think.

**Comment by KC031** [comment]
I wanted to come back on this issue, a couple of years on. This solution has worked forever for me, but I updated the client today and of course it disappeared and cost me a lot of time to find back what happened.

I was wondering if there would be any better solution for this that can be implemented in the source code? I would like to also refer to the documentation, which shows that for this endpoint, you can only use the post method: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=InventoryProcessStockCount
