### ISSUE TITLE
Limiting syncItems result set

### ISSUE THREAD

**Issue by bramhoepCM** [picqer/exact-php-client#587]
Is there a way to prevent calling the next url after retrieving 2 sets of a 1000.

In total we have 10000 articles in exact and we would like to get only a set of 2 thousand instead of the whole 10 thousand.

We've tried the following:

```
$itemConnection = new \Picqer\Financials\Exact\SyncItem($connection);
$itemsNL = $itemConnection->filter('Timestamp gt '.$timestamp.'L', '', implode(',', $itemConnection->getFillable()), '$top=2000');
// Still getting all the results back.

$itemsNL = $itemConnection->filter('Timestamp gt '.$timestamp.'L', '', implode(',', $itemConnection->getFillable()), '', ['$top' => 2000]);
// Still getting all the results back.
```

Any suggestions would help.

**Comment by DannyvdSluijs** [comment]
I've spent some time to look into this, the oData part of the API is still a bit unknown to me and the explanation from Exact is not that extensive. With regards to the `top 2000` in `src/Picqer/Financials/Exact/Query/Findable.php:113` it shows that the `$system_query_options` is checked for being an array. So from your first example (`'$top=2000'`) the top  is not taken into account.

One remark from the comments I see the `$select` isn't supported.

So it seems 
```
$itemsNL = $itemConnection->filter('Timestamp gt '.$timestamp.'L', '', '', '', ['$top' => 2000]);
```

Would be the correct code. This sends a request using the url `https://start.exactonline.nl/api/v1/1234/sync/Logistics/Items?%24top=2000&%24filter=Timestamp+gt+1669709492L`

If this doesn't solve the issue I would recommend raising an issue with Exact Online support to see what the issue is with the request. And let us know as wel can then make sure the correction is reflected in the code.

**Comment by bramhoepCM** [comment]
@DannyvdSluijs 

Het probleem speelt nu weer bij een klant en we hebben er weer even goed naar gekeken.

We hebben de oplossing gevonden en dat is:
`$itemsNL = $itemConnection->filter('Timestamp gt '.$timestamp.'L', '', 'ID', ['$top' => '5']);`

We sturen hem dus mee bij de query_options array en niet bij de headers.
