### ISSUE TITLE
Error 400: Expression of type 'System.Boolean' expected at position 0.

### ISSUE THREAD

**Issue by teunLoile** [picqer/exact-php-client#593]
**Running into an bug after the exact online update**

here is the error

`Picqer\Financials\Exact\ApiException: Error 400: Expression of type 'System.Boolean' expected at position 0. in file C:\laragon\www\configurator\app\Http\Controllers\SaveExactCodeController.php on line 114`

my code 
![image](https://user-images.githubusercontent.com/108728782/200374178-f9773353-e252-4986-804b-5b641ef1117a.png)

Im wondering why this is not working can some one help me? This started apearing after the exact update. I have seen issues with the same problem but when I add a $filter it seems to give this system boolean error. Any one know what is happening here. The screen shot is the entire function.

**Comment by DannyvdSluijs** [comment]
Hi @teunLoile 

Generally I think it would help if you can provide more details, such as line numbers and which update you’re referring to. 
Also this project is an open source maintained project and has no direct affiliation with ExactOnline if you believe the issue is on the API side I would recommend getting in touch with their customer support.
