### ISSUE TITLE
Error: Typed property Picqer\Financials\Exact\Connection::$minutelyLimitReset must not be accessed before initialization

### ISSUE THREAD

**Issue by jegelkraut** [picqer/exact-php-client#633]
Hello,

since upgrading to version 4.3.0 (released today) I get this error when setting

`$connection->setWaitOnMinutelyRateLimitHit(true);`

to true: 

> Error: Typed property Picqer\Financials\Exact\Connection::$minutelyLimitReset must not be accessed before initialization

I guess this was introduced with type hinting #625 and $minutelyLimitReset is accessed before the actual request which sets it after parsing the headers.

**Comment by remkobrenters** [comment]
Hmm that is an unexpected but logical issue. @DannyvdSluijs can you look into this?

**Comment by DannyvdSluijs** [comment]
#634 should resolve the bug. The issue is not directly triggered by `$connection->setWaitOnMinutelyRateLimitHit(true);` but this is causing `::waitIfMinutelyRateLimitHit()` to be executed in full instead of following the early return. In the alternative codepath the `::getMinutelyLimitReset` is being called. 

I also noticed the other properties related to the limit would have the same issue and addressed them in the same PR as well.

**Comment by jegelkraut** [comment]
Thanks a lot for the ultra fast response and fix! Great library!
