### ISSUE TITLE
Strict type error

### ISSUE THREAD

**Issue by i-shippi** [picqer/exact-php-client#641]
Hello, after version 4.3 you added strict type in your files and that introduced a bug in src/Picqer/Financials/Exact/Query/Findable.php trait line 67.

The function that has the bug, is **findId** and if the first argument is an int , the code breaks when calling preg_match because of the strict type declaration. I can't provide a string as the $code argument with combination of the $key argument necessary for searching in exact online, because exact online gives back an error.

Since the first argument of the function allows integers as first argument, it would make sense to fix this by adding an extra condition at line 67 by checking if $code is a string before calling preg_match on it.

**Comment by DannyvdSluijs** [comment]
The code being referred to can be found [here](https://github.com/picqer/exact-php-client/blob/main/src/Picqer/Financials/Exact/Query/Findable.php#L55-L84)

As a side note you can see the function docblock mentions`$code` to be of type string.
```php
@param string $code the value to search for
``` 
If this would be turned into a native typehint in PHP it would enforce the calling code to pass a string. So the integer is rather unexpected at this point in the code.

Which I would assume is an indicator that passing an int isn't a option. The fact that downstream Exact Online will throw an exception is much more interesting as that is unexpected.

**Comment by DannyvdSluijs** [comment]
So If I understand correctly you want to invoke `findId()` with  a integer value for `$code` (Let's assume `42` for this example) and the literal string `YourRef` passed as a value for `$key` which should invoke the API endpoint with the query paramater `$filter=YourRef eq 42`

This is how it used to work before [version 4.3](https://github.com/picqer/exact-php-client/releases/tag/v4.3.0) and is broken since? 

---
Also:
`YourRef`(as per your example)  is a property in the 36 endpoints, some listed below:
- https://start.exactonline.nl//docs//HlpRestAPIResourcesDetails.aspx?name=BulkCashflowPayments
- https://start.exactonline.nl//docs//HlpRestAPIResourcesDetails.aspx?name=BulkCashflowReceivables
- https://start.exactonline.nl//docs//HlpRestAPIResourcesDetails.aspx?name=BulkCRMQuotations
- https://start.exactonline.nl//docs//HlpRestAPIResourcesDetails.aspx?name=BulkFinancialTransactionLines
- https://start.exactonline.nl//docs//HlpRestAPIResourcesDetails.aspx?name=BulkSalesInvoiceSalesInvoices

In all occasions the `YourRef` property is defined in the ExactOnline API as a string property. So searching for an integer would only lead to an implicit conversion on the Exact Online side of things.

---
I guess this issue report can greatly benefit of some reproduction steps in order to fix it correctly. And secondly you briefly mentioned:
>I can't provide a string as the $code argument with combination of the $key argument necessary for searching in exact online, because exact online gives back an error.
I think sharing more about the details of this error would be helping the context here as well.

**Comment by i-shippi** [comment]
Yes that is correct. Before version 4.3, the query parameter was `$filter=YourRef eq 42` because I was providing an int as the $code argument.
From version 4.3 the same code gives an error because of preg_match first argument being an int instead of string.
When I try to provide $code as string, with version 4.3, the query parameter is `$filter=YourRef eq '42'` and exact online returns an error.

Not sure if some other value for $key requires the $code to be wrapped in single quotes but for this specific case, I can't update the library in my code base because it breaks my specific search.

**Comment by i-shippi** [comment]
The example I gave that gives the error was wrong.
The error is happening when trying to search for `EntryNumber` for a [CashEntry](https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=FinancialTransactionCashEntries)

I apologize for the wrong example because it was misleading. As you can see from the exact online docs, that property is an int.

I have created a [PR](https://github.com/picqer/exact-php-client/pull/643) that fixes this error since in this example $code should not be wrapped around single quotes and it is an int

**Comment by DannyvdSluijs** [comment]
I'm only a contributor and don't have any permission to merge PR's.
Typically @remkobrenters is the one that reviews and approves them and then @stephangroen comes by and does a merge and release (if needed).

**Comment by remkobrenters** [comment]
Sorry for ignoring the PR. Was busy. Checked it out and looks good to me. Did not test it myself.

**Comment by i-shippi** [comment]
@remkobrenters I have tested the changes on our codebase and I don't get the error anymore and everything else goes fine. I don't expect something else to be broken since the change was really specific to the strict type error.

**Comment by remkobrenters** [comment]
Nice. Will close this issue. Thanks for pointing it out and the solution.
