### ISSUE TITLE
Parsing Results

### ISSUE THREAD

**Issue by dassaffe** [picqer/exact-php-client#78]
Hey, great work so far, works as expected and it is easy to handle.
However, I have a question which I can't answer myself.

I'm using your code like this:

```
$item = new \Picqer\Financials\Exact\SalesInvoice($connection);
$items = $item->filter("InvoiceToName eq 'Some name'");
```

And I get a response, however, do you offer something to parse it? Because it is returned as one long string and I can't access it via 

```
$items["attributes"] 
```

or something like this.

**Comment by stephangroen** [comment]
That call should return an array of SalesInvoice objects. You can access them by magic method:

```
$item = new \Picqer\Financials\Exact\SalesInvoice($connection);
$items = $item->filter("InvoiceToName eq 'Some name'");

foreach ($items as $i) {
    $invoiceDate = $i->InvoiceDate;
}
```

**Comment by dassaffe** [comment]
@stephangroen Mind if you show an example on how to use Documents? I read the docs but I can't follow that:

For instance, I'm using the SalesInvoice, and regarding to their docs, there is a field "Document", which is also available in the class. However, printing

```
foreach($items as $i) {
    var_dump($i->Document)
}
```
returns just null. 
What I want to achieve is:
Get all Documents related to the current SalesInvoice. 
Any idea?

**Comment by stephangroen** [comment]
I have never used a document linked to a SalesInvoice, but checking the docs it seems that 'Document' is a GUID reference to a single Document that is manually linked to the invoice by the user. Since you're talking about multiple attachments, it seems this is not the right property.

Maybe you need to use DocumentFolder which can contain multiple Documents, but I have no personal experience with this part of the API. You could submit a support ticket to Exact and ask how this is achieved via the API. Unfortunately their docs aren't that comprehensive.
