### ISSUE TITLE
Fatal Error : 400 Bad Request

### ISSUE THREAD

**Issue by kingcoen** [picqer/exact-php-client#96]
Hi,

I run into an error while making an connection. I use the example to make a connection and I got the following issue : 

`Fatal error: Uncaught Exception: Could not connect to Exact: Client error: `POST https://start.exactonline.nl/api/oauth2/token` resulted in a `400 Bad Request` response: Bad Request in /var/www/html/oauth_call_connect.php:61 Stack trace: #0 {main} thrown in /var/www/html/oauth_call_connect.php on line 61`

Any help?

**Comment by kingcoen** [comment]
For some reason when I run it in Postman it works and it generates an accesstoken. Can anyone tell me why it isn't generated when I visit it in my browser?

**Comment by alexjeen** [comment]
This mostly happens when you try to reuse the "code" you get back from Exact Online. The code you get on your redirection URL is only valid "once". So the next time you do the request, this code won't work anymore (if you authenticate with that code, you will get an error stating the 400 bad request).

**Comment by alexjeen** [comment]
See the updated documentation!

**Comment by stephangroen** [comment]
@kingcoen Did @alexjeen's comments help you?

**Comment by kingcoen** [comment]
Yes! It did! Thanks!
