### ISSUE TITLE
Small fix in documentation

### ISSUE THREAD

**Issue by alexjeen** [picqer/exact-php-client#98]
Todo mentions:

* Switch administration (now uses default)

However switching division already works as expected:

        $connection = \app\models\Exact::connect(\app\models\Credential::findOne(1));
        $connection->setDivision(123456);

        $account = new \Picqer\Financials\Exact\Account($connection);
        $account->Name = 'Alex';
        $account->Status = 'C';
        var_dump($account->save());

**Comment by mplus-software** [comment]
Perhaps [this issue](https://github.com/picqer/exact-php-client/issues/99) shines light on that TODO point? 

If you don't specifiy a division through setDivision, the client always defaults to the Division that the user of the Exact webapp is currently working in. Which means that it changes everytime the user of the webapp changes Divisions.

This can cause some very unexpected behaviour if you're not aware.

**Comment by alexjeen** [comment]
Maybe I can make a Pull-request where I change the README to encapsulate some more examples in switching divisions? What do you think?

**Comment by mplus-software** [comment]
Yes, sounds good.

I think the problem with the current examples is that after you have the proper tokens set-up and are connected, it immediately jumps into how to create accounts and products.

But setting the proper Division before that must not be skipped, because otherwise the accounts and products you create can end up in different Divisions depending on what the user is doing in the webapp.

**Comment by alexjeen** [comment]
See PR #100
